version: '3.8'

services:
  django-auth:
    image: compose-django.mysql:latest
    container_name: django-auth
    build:
      context: ./auth_service_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "static_db:/static"
    depends_on:
      - mysql

  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: 'dbtest'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - my_db:/var/lib/mysql

  django-web-app:
    image: compose-django-mongo:latest
    container_name: django-web-app
    build:
      context: ./web_services_app
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - "static_db:/static"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"

  nginx:
    image: nginx-ms:latest
    build:
        context: ./proxy_server
        dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    volumes:
      - nginx_config:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - django-auth
      - django-web-app

volumes:
  my_db:
    name: my_db
  static_db:
    name: static_db
  mongo_db:
  nginx_config:
    name: nginx_config


